package mx.redhat.ericsson.dtra.entidades;

// Generated 27/08/2015 12:50:18 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Engineer generated by hbm2java
 */
@Entity
@Table(name = "engineer", schema = "public")
public class Engineer implements java.io.Serializable {

	private long engineerId;
	private Short status;
	private Integer corporateId;
	private String lastName;
	private String firstName;
	private String knowAs;
	private String emailAddress;
	private Integer country;
	private Integer primaryOrg;
	private Integer companyCode;
	private String orgUnitShort;
	private String nameOfSuperior;
	private Integer persNoOfSuperior;
	private String idOfSuperior;
	private String personnelSubarea;
	private Long costCenter;
	private Integer unit;
	private Serializable competences;
	private Long engineerProfile;
	private Integer indexOfEnginnerExpertise;
	private Integer calendar;

	public Engineer() {
	}

	public Engineer(long engineerId) {
		this.engineerId = engineerId;
	}

	public Engineer(long engineerId, Short status, Integer corporateId,
			String lastName, String firstName, String knowAs,
			String emailAddress, Integer country, Integer primaryOrg,
			Integer companyCode, String orgUnitShort, String nameOfSuperior,
			Integer persNoOfSuperior, String idOfSuperior,
			String personnelSubarea, Long costCenter, Integer unit,
			Serializable competences, Long engineerProfile,
			Integer indexOfEnginnerExpertise, Integer calendar) {
		this.engineerId = engineerId;
		this.status = status;
		this.corporateId = corporateId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.knowAs = knowAs;
		this.emailAddress = emailAddress;
		this.country = country;
		this.primaryOrg = primaryOrg;
		this.companyCode = companyCode;
		this.orgUnitShort = orgUnitShort;
		this.nameOfSuperior = nameOfSuperior;
		this.persNoOfSuperior = persNoOfSuperior;
		this.idOfSuperior = idOfSuperior;
		this.personnelSubarea = personnelSubarea;
		this.costCenter = costCenter;
		this.unit = unit;
		this.competences = competences;
		this.engineerProfile = engineerProfile;
		this.indexOfEnginnerExpertise = indexOfEnginnerExpertise;
		this.calendar = calendar;
	}

	@Id
	@Column(name = "engineer_id", unique = true, nullable = false)
	public long getEngineerId() {
		return this.engineerId;
	}

	public void setEngineerId(long engineerId) {
		this.engineerId = engineerId;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Column(name = "corporate_id")
	public Integer getCorporateId() {
		return this.corporateId;
	}

	public void setCorporateId(Integer corporateId) {
		this.corporateId = corporateId;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "know_as")
	public String getKnowAs() {
		return this.knowAs;
	}

	public void setKnowAs(String knowAs) {
		this.knowAs = knowAs;
	}

	@Column(name = "email_address")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "country")
	public Integer getCountry() {
		return this.country;
	}

	public void setCountry(Integer country) {
		this.country = country;
	}

	@Column(name = "primary_org")
	public Integer getPrimaryOrg() {
		return this.primaryOrg;
	}

	public void setPrimaryOrg(Integer primaryOrg) {
		this.primaryOrg = primaryOrg;
	}

	@Column(name = "company_code")
	public Integer getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(Integer companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "org_unit_short")
	public String getOrgUnitShort() {
		return this.orgUnitShort;
	}

	public void setOrgUnitShort(String orgUnitShort) {
		this.orgUnitShort = orgUnitShort;
	}

	@Column(name = "name_of_superior")
	public String getNameOfSuperior() {
		return this.nameOfSuperior;
	}

	public void setNameOfSuperior(String nameOfSuperior) {
		this.nameOfSuperior = nameOfSuperior;
	}

	@Column(name = "pers_no_of_superior")
	public Integer getPersNoOfSuperior() {
		return this.persNoOfSuperior;
	}

	public void setPersNoOfSuperior(Integer persNoOfSuperior) {
		this.persNoOfSuperior = persNoOfSuperior;
	}

	@Column(name = "id_of_superior")
	public String getIdOfSuperior() {
		return this.idOfSuperior;
	}

	public void setIdOfSuperior(String idOfSuperior) {
		this.idOfSuperior = idOfSuperior;
	}

	@Column(name = "personnel_subarea")
	public String getPersonnelSubarea() {
		return this.personnelSubarea;
	}

	public void setPersonnelSubarea(String personnelSubarea) {
		this.personnelSubarea = personnelSubarea;
	}

	@Column(name = "cost_center")
	public Long getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(Long costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "competences")
	public Serializable getCompetences() {
		return this.competences;
	}

	public void setCompetences(Serializable competences) {
		this.competences = competences;
	}

	@Column(name = "engineer_profile")
	public Long getEngineerProfile() {
		return this.engineerProfile;
	}

	public void setEngineerProfile(Long engineerProfile) {
		this.engineerProfile = engineerProfile;
	}

	@Column(name = "index_of_enginner_expertise")
	public Integer getIndexOfEnginnerExpertise() {
		return this.indexOfEnginnerExpertise;
	}

	public void setIndexOfEnginnerExpertise(Integer indexOfEnginnerExpertise) {
		this.indexOfEnginnerExpertise = indexOfEnginnerExpertise;
	}

	@Column(name = "calendar")
	public Integer getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Integer calendar) {
		this.calendar = calendar;
	}

}
