package mx.redhat.ericsson.dtra.entidades;

// Generated 27/08/2015 12:50:18 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WorkPackage generated by hbm2java
 */
@Entity
@Table(name = "work_package", schema = "public")
public class WorkPackage implements java.io.Serializable {

	private String wpId;
	private String wpName;
	private Integer wpCategory;
	private Integer wpNormHours;
	private Integer wpLeadTime;
	private String wpRelease;
	private Integer wpStatus;
	private Long orderingOrigin;
	private Integer deliveryUnit;

	public WorkPackage() {
	}

	public WorkPackage(String wpId) {
		this.wpId = wpId;
	}

	public WorkPackage(String wpId, String wpName, Integer wpCategory,
			Integer wpNormHours, Integer wpLeadTime, String wpRelease,
			Integer wpStatus, Long orderingOrigin, Integer deliveryUnit) {
		this.wpId = wpId;
		this.wpName = wpName;
		this.wpCategory = wpCategory;
		this.wpNormHours = wpNormHours;
		this.wpLeadTime = wpLeadTime;
		this.wpRelease = wpRelease;
		this.wpStatus = wpStatus;
		this.orderingOrigin = orderingOrigin;
		this.deliveryUnit = deliveryUnit;
	}

	@Id
	@Column(name = "wp_id", unique = true, nullable = false, length = 10)
	public String getWpId() {
		return this.wpId;
	}

	public void setWpId(String wpId) {
		this.wpId = wpId;
	}

	@Column(name = "wp_name", length = 100)
	public String getWpName() {
		return this.wpName;
	}

	public void setWpName(String wpName) {
		this.wpName = wpName;
	}

	@Column(name = "wp_category")
	public Integer getWpCategory() {
		return this.wpCategory;
	}

	public void setWpCategory(Integer wpCategory) {
		this.wpCategory = wpCategory;
	}

	@Column(name = "wp_norm_hours")
	public Integer getWpNormHours() {
		return this.wpNormHours;
	}

	public void setWpNormHours(Integer wpNormHours) {
		this.wpNormHours = wpNormHours;
	}

	@Column(name = "wp_lead_time")
	public Integer getWpLeadTime() {
		return this.wpLeadTime;
	}

	public void setWpLeadTime(Integer wpLeadTime) {
		this.wpLeadTime = wpLeadTime;
	}

	@Column(name = "wp_release", length = 10)
	public String getWpRelease() {
		return this.wpRelease;
	}

	public void setWpRelease(String wpRelease) {
		this.wpRelease = wpRelease;
	}

	@Column(name = "wp_status")
	public Integer getWpStatus() {
		return this.wpStatus;
	}

	public void setWpStatus(Integer wpStatus) {
		this.wpStatus = wpStatus;
	}

	@Column(name = "ordering_origin")
	public Long getOrderingOrigin() {
		return this.orderingOrigin;
	}

	public void setOrderingOrigin(Long orderingOrigin) {
		this.orderingOrigin = orderingOrigin;
	}

	@Column(name = "delivery_unit")
	public Integer getDeliveryUnit() {
		return this.deliveryUnit;
	}

	public void setDeliveryUnit(Integer deliveryUnit) {
		this.deliveryUnit = deliveryUnit;
	}

}
