package mx.redhat.ericsson.dtra.entities;

// Generated 1/09/2015 05:13:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", schema = "public")
public class Activity implements java.io.Serializable {

	private long w6key;
	private String actname;
	private Integer duration;
	private Integer timeinpreviousstatus;
	private Integer engineertype;
	private String businessstructurelookup;
	private Integer priority;
	private String preferredEngineers;
	private String requiredEngnineers;
	private Integer gsc;
	private Integer unit;
	private Integer subunit;
	private Integer region;
	private Integer disctrict;
	private Date earlystart;
	private Date latestart;
	private Date duedate;
	private String activityid;
	private String workpackage;
	private String workpackagegroup;

	public Activity() {
	}

	public Activity(long w6key) {
		this.w6key = w6key;
	}

	public Activity(long w6key, String actname, Integer duration,
			Integer timeinpreviousstatus, Integer engineertype,
			String businessstructurelookup, Integer priority,
			String preferredEngineers, String requiredEngnineers, Integer gsc,
			Integer unit, Integer subunit, Integer region, Integer disctrict,
			Date earlystart, Date latestart, Date duedate, String activityid,
			String workpackage, String workpackagegroup) {
		this.w6key = w6key;
		this.actname = actname;
		this.duration = duration;
		this.timeinpreviousstatus = timeinpreviousstatus;
		this.engineertype = engineertype;
		this.businessstructurelookup = businessstructurelookup;
		this.priority = priority;
		this.preferredEngineers = preferredEngineers;
		this.requiredEngnineers = requiredEngnineers;
		this.gsc = gsc;
		this.unit = unit;
		this.subunit = subunit;
		this.region = region;
		this.disctrict = disctrict;
		this.earlystart = earlystart;
		this.latestart = latestart;
		this.duedate = duedate;
		this.activityid = activityid;
		this.workpackage = workpackage;
		this.workpackagegroup = workpackagegroup;
	}

	@Id
	@Column(name = "w6key", unique = true, nullable = false)
	public long getW6key() {
		return this.w6key;
	}

	public void setW6key(long w6key) {
		this.w6key = w6key;
	}

	@Column(name = "actname", length = 200)
	public String getActname() {
		return this.actname;
	}

	public void setActname(String actname) {
		this.actname = actname;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "timeinpreviousstatus")
	public Integer getTimeinpreviousstatus() {
		return this.timeinpreviousstatus;
	}

	public void setTimeinpreviousstatus(Integer timeinpreviousstatus) {
		this.timeinpreviousstatus = timeinpreviousstatus;
	}

	@Column(name = "engineertype")
	public Integer getEngineertype() {
		return this.engineertype;
	}

	public void setEngineertype(Integer engineertype) {
		this.engineertype = engineertype;
	}

	@Column(name = "businessstructurelookup", length = 500)
	public String getBusinessstructurelookup() {
		return this.businessstructurelookup;
	}

	public void setBusinessstructurelookup(String businessstructurelookup) {
		this.businessstructurelookup = businessstructurelookup;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "preferred_engineers", length = 500)
	public String getPreferredEngineers() {
		return this.preferredEngineers;
	}

	public void setPreferredEngineers(String preferredEngineers) {
		this.preferredEngineers = preferredEngineers;
	}

	@Column(name = "required_engnineers", length = 500)
	public String getRequiredEngnineers() {
		return this.requiredEngnineers;
	}

	public void setRequiredEngnineers(String requiredEngnineers) {
		this.requiredEngnineers = requiredEngnineers;
	}

	@Column(name = "gsc")
	public Integer getGsc() {
		return this.gsc;
	}

	public void setGsc(Integer gsc) {
		this.gsc = gsc;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "subunit")
	public Integer getSubunit() {
		return this.subunit;
	}

	public void setSubunit(Integer subunit) {
		this.subunit = subunit;
	}

	@Column(name = "region")
	public Integer getRegion() {
		return this.region;
	}

	public void setRegion(Integer region) {
		this.region = region;
	}

	@Column(name = "disctrict")
	public Integer getDisctrict() {
		return this.disctrict;
	}

	public void setDisctrict(Integer disctrict) {
		this.disctrict = disctrict;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "earlystart", length = 13)
	public Date getEarlystart() {
		return this.earlystart;
	}

	public void setEarlystart(Date earlystart) {
		this.earlystart = earlystart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "latestart", length = 13)
	public Date getLatestart() {
		return this.latestart;
	}

	public void setLatestart(Date latestart) {
		this.latestart = latestart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "duedate", length = 13)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	@Column(name = "activityid", length = 40)
	public String getActivityid() {
		return this.activityid;
	}

	public void setActivityid(String activityid) {
		this.activityid = activityid;
	}

	@Column(name = "workpackage", length = 40)
	public String getWorkpackage() {
		return this.workpackage;
	}

	public void setWorkpackage(String workpackage) {
		this.workpackage = workpackage;
	}

	@Column(name = "workpackagegroup", length = 40)
	public String getWorkpackagegroup() {
		return this.workpackagegroup;
	}

	public void setWorkpackagegroup(String workpackagegroup) {
		this.workpackagegroup = workpackagegroup;
	}

}
