package mx.redhat.ericsson.dtra.entities;

// Generated 1/09/2015 05:13:08 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EngineerCompetence generated by hbm2java
 */
@Entity
@Table(name = "engineer_competence", schema = "public")
public class EngineerCompetence implements java.io.Serializable {

	private EngineerCompetenceId id;

	public EngineerCompetence() {
	}

	public EngineerCompetence(EngineerCompetenceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "w6key", column = @Column(name = "w6key")),
			@AttributeOverride(name = "competencesubdomain", column = @Column(name = "competencesubdomain")),
			@AttributeOverride(name = "servicearea", column = @Column(name = "servicearea")),
			@AttributeOverride(name = "jobrole", column = @Column(name = "jobrole")),
			@AttributeOverride(name = "jobrolestage", column = @Column(name = "jobrolestage")) })
	public EngineerCompetenceId getId() {
		return this.id;
	}

	public void setId(EngineerCompetenceId id) {
		this.id = id;
	}

}
