package mx.redhat.ericsson.dtra.entities;

// Generated 1/09/2015 05:13:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Engineer generated by hbm2java
 */
@Entity
@Table(name = "engineer", schema = "public")
public class Engineer implements java.io.Serializable {

	private long w6key;
	private Short active;
	private Integer gsc;
	private Integer unit;
	private Integer subunit;
	private Integer region;
	private Integer disctrict;
	private Integer calendar;

	public Engineer() {
	}

	public Engineer(long w6key) {
		this.w6key = w6key;
	}

	public Engineer(long w6key, Short active, Integer gsc, Integer unit,
			Integer subunit, Integer region, Integer disctrict, Integer calendar) {
		this.w6key = w6key;
		this.active = active;
		this.gsc = gsc;
		this.unit = unit;
		this.subunit = subunit;
		this.region = region;
		this.disctrict = disctrict;
		this.calendar = calendar;
	}

	@Id
	@Column(name = "w6key", unique = true, nullable = false)
	public long getW6key() {
		return this.w6key;
	}

	public void setW6key(long w6key) {
		this.w6key = w6key;
	}

	@Column(name = "active")
	public Short getActive() {
		return this.active;
	}

	public void setActive(Short active) {
		this.active = active;
	}

	@Column(name = "gsc")
	public Integer getGsc() {
		return this.gsc;
	}

	public void setGsc(Integer gsc) {
		this.gsc = gsc;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "subunit")
	public Integer getSubunit() {
		return this.subunit;
	}

	public void setSubunit(Integer subunit) {
		this.subunit = subunit;
	}

	@Column(name = "region")
	public Integer getRegion() {
		return this.region;
	}

	public void setRegion(Integer region) {
		this.region = region;
	}

	@Column(name = "disctrict")
	public Integer getDisctrict() {
		return this.disctrict;
	}

	public void setDisctrict(Integer disctrict) {
		this.disctrict = disctrict;
	}

	@Column(name = "calendar")
	public Integer getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Integer calendar) {
		this.calendar = calendar;
	}

}
