package mx.redhat.ericsson.dtra.entities;

// Generated 1/09/2015 05:13:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EngineerCompetenceId generated by hbm2java
 */
@Embeddable
public class EngineerCompetenceId implements java.io.Serializable {

	private Long w6key;
	private Integer competencesubdomain;
	private Integer servicearea;
	private Integer jobrole;
	private Integer jobrolestage;

	public EngineerCompetenceId() {
	}

	public EngineerCompetenceId(Long w6key, Integer competencesubdomain,
			Integer servicearea, Integer jobrole, Integer jobrolestage) {
		this.w6key = w6key;
		this.competencesubdomain = competencesubdomain;
		this.servicearea = servicearea;
		this.jobrole = jobrole;
		this.jobrolestage = jobrolestage;
	}

	@Column(name = "w6key")
	public Long getW6key() {
		return this.w6key;
	}

	public void setW6key(Long w6key) {
		this.w6key = w6key;
	}

	@Column(name = "competencesubdomain")
	public Integer getCompetencesubdomain() {
		return this.competencesubdomain;
	}

	public void setCompetencesubdomain(Integer competencesubdomain) {
		this.competencesubdomain = competencesubdomain;
	}

	@Column(name = "servicearea")
	public Integer getServicearea() {
		return this.servicearea;
	}

	public void setServicearea(Integer servicearea) {
		this.servicearea = servicearea;
	}

	@Column(name = "jobrole")
	public Integer getJobrole() {
		return this.jobrole;
	}

	public void setJobrole(Integer jobrole) {
		this.jobrole = jobrole;
	}

	@Column(name = "jobrolestage")
	public Integer getJobrolestage() {
		return this.jobrolestage;
	}

	public void setJobrolestage(Integer jobrolestage) {
		this.jobrolestage = jobrolestage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EngineerCompetenceId))
			return false;
		EngineerCompetenceId castOther = (EngineerCompetenceId) other;

		return ((this.getW6key() == castOther.getW6key()) || (this.getW6key() != null
				&& castOther.getW6key() != null && this.getW6key().equals(
				castOther.getW6key())))
				&& ((this.getCompetencesubdomain() == castOther
						.getCompetencesubdomain()) || (this
						.getCompetencesubdomain() != null
						&& castOther.getCompetencesubdomain() != null && this
						.getCompetencesubdomain().equals(
								castOther.getCompetencesubdomain())))
				&& ((this.getServicearea() == castOther.getServicearea()) || (this
						.getServicearea() != null
						&& castOther.getServicearea() != null && this
						.getServicearea().equals(castOther.getServicearea())))
				&& ((this.getJobrole() == castOther.getJobrole()) || (this
						.getJobrole() != null && castOther.getJobrole() != null && this
						.getJobrole().equals(castOther.getJobrole())))
				&& ((this.getJobrolestage() == castOther.getJobrolestage()) || (this
						.getJobrolestage() != null
						&& castOther.getJobrolestage() != null && this
						.getJobrolestage().equals(castOther.getJobrolestage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getW6key() == null ? 0 : this.getW6key().hashCode());
		result = 37
				* result
				+ (getCompetencesubdomain() == null ? 0 : this
						.getCompetencesubdomain().hashCode());
		result = 37
				* result
				+ (getServicearea() == null ? 0 : this.getServicearea()
						.hashCode());
		result = 37 * result
				+ (getJobrole() == null ? 0 : this.getJobrole().hashCode());
		result = 37
				* result
				+ (getJobrolestage() == null ? 0 : this.getJobrolestage()
						.hashCode());
		return result;
	}

}
